// Code generated by go-swagger; DO NOT EDIT.

package peers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/atotto/skyway-webrtc-gateway-go-client/models"
)

// NewPeerParams creates a new PeerParams object
// with the default values initialized.
func NewPeerParams() *PeerParams {
	var ()
	return &PeerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPeerParamsWithTimeout creates a new PeerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPeerParamsWithTimeout(timeout time.Duration) *PeerParams {
	var ()
	return &PeerParams{

		timeout: timeout,
	}
}

// NewPeerParamsWithContext creates a new PeerParams object
// with the default values initialized, and the ability to set a context for a request
func NewPeerParamsWithContext(ctx context.Context) *PeerParams {
	var ()
	return &PeerParams{

		Context: ctx,
	}
}

// NewPeerParamsWithHTTPClient creates a new PeerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPeerParamsWithHTTPClient(client *http.Client) *PeerParams {
	var ()
	return &PeerParams{
		HTTPClient: client,
	}
}

/*PeerParams contains all the parameters to send to the API endpoint
for the peer operation typically these are written to a http.Request
*/
type PeerParams struct {

	/*Body
	  SkyWayサーバへアクセスするための情報を指定します。Peerの認証機能が有効になっている場合は、クレデンシャルが必要です

	*/
	Body *models.PeerOptions

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the peer params
func (o *PeerParams) WithTimeout(timeout time.Duration) *PeerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the peer params
func (o *PeerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the peer params
func (o *PeerParams) WithContext(ctx context.Context) *PeerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the peer params
func (o *PeerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the peer params
func (o *PeerParams) WithHTTPClient(client *http.Client) *PeerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the peer params
func (o *PeerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the peer params
func (o *PeerParams) WithBody(body *models.PeerOptions) *PeerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the peer params
func (o *PeerParams) SetBody(body *models.PeerOptions) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PeerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
