// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMediaConnectionStatusParams creates a new MediaConnectionStatusParams object
// with the default values initialized.
func NewMediaConnectionStatusParams() *MediaConnectionStatusParams {
	var ()
	return &MediaConnectionStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMediaConnectionStatusParamsWithTimeout creates a new MediaConnectionStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMediaConnectionStatusParamsWithTimeout(timeout time.Duration) *MediaConnectionStatusParams {
	var ()
	return &MediaConnectionStatusParams{

		timeout: timeout,
	}
}

// NewMediaConnectionStatusParamsWithContext creates a new MediaConnectionStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewMediaConnectionStatusParamsWithContext(ctx context.Context) *MediaConnectionStatusParams {
	var ()
	return &MediaConnectionStatusParams{

		Context: ctx,
	}
}

// NewMediaConnectionStatusParamsWithHTTPClient creates a new MediaConnectionStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMediaConnectionStatusParamsWithHTTPClient(client *http.Client) *MediaConnectionStatusParams {
	var ()
	return &MediaConnectionStatusParams{
		HTTPClient: client,
	}
}

/*MediaConnectionStatusParams contains all the parameters to send to the API endpoint
for the media connection status operation typically these are written to a http.Request
*/
type MediaConnectionStatusParams struct {

	/*MediaConnectionID
	  MediaConnectionを特定するためのIDを指定します

	*/
	MediaConnectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the media connection status params
func (o *MediaConnectionStatusParams) WithTimeout(timeout time.Duration) *MediaConnectionStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the media connection status params
func (o *MediaConnectionStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the media connection status params
func (o *MediaConnectionStatusParams) WithContext(ctx context.Context) *MediaConnectionStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the media connection status params
func (o *MediaConnectionStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the media connection status params
func (o *MediaConnectionStatusParams) WithHTTPClient(client *http.Client) *MediaConnectionStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the media connection status params
func (o *MediaConnectionStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMediaConnectionID adds the mediaConnectionID to the media connection status params
func (o *MediaConnectionStatusParams) WithMediaConnectionID(mediaConnectionID string) *MediaConnectionStatusParams {
	o.SetMediaConnectionID(mediaConnectionID)
	return o
}

// SetMediaConnectionID adds the mediaConnectionId to the media connection status params
func (o *MediaConnectionStatusParams) SetMediaConnectionID(mediaConnectionID string) {
	o.MediaConnectionID = mediaConnectionID
}

// WriteToRequest writes these params to a swagger request
func (o *MediaConnectionStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param media_connection_id
	if err := r.SetPathParam("media_connection_id", o.MediaConnectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
