// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/atotto/skyway-webrtc-gateway-go-client/models"
)

// NewMediaParams creates a new MediaParams object
// with the default values initialized.
func NewMediaParams() *MediaParams {
	var ()
	return &MediaParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMediaParamsWithTimeout creates a new MediaParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMediaParamsWithTimeout(timeout time.Duration) *MediaParams {
	var ()
	return &MediaParams{

		timeout: timeout,
	}
}

// NewMediaParamsWithContext creates a new MediaParams object
// with the default values initialized, and the ability to set a context for a request
func NewMediaParamsWithContext(ctx context.Context) *MediaParams {
	var ()
	return &MediaParams{

		Context: ctx,
	}
}

// NewMediaParamsWithHTTPClient creates a new MediaParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMediaParamsWithHTTPClient(client *http.Client) *MediaParams {
	var ()
	return &MediaParams{
		HTTPClient: client,
	}
}

/*MediaParams contains all the parameters to send to the API endpoint
for the media operation typically these are written to a http.Request
*/
type MediaParams struct {

	/*Body
	  Mediaの種類を指定します

	*/
	Body *models.MediaOptions

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the media params
func (o *MediaParams) WithTimeout(timeout time.Duration) *MediaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the media params
func (o *MediaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the media params
func (o *MediaParams) WithContext(ctx context.Context) *MediaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the media params
func (o *MediaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the media params
func (o *MediaParams) WithHTTPClient(client *http.Client) *MediaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the media params
func (o *MediaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the media params
func (o *MediaParams) WithBody(body *models.MediaOptions) *MediaParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the media params
func (o *MediaParams) SetBody(body *models.MediaOptions) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *MediaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
