// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMediaRtcpCreateParams creates a new MediaRtcpCreateParams object
// with the default values initialized.
func NewMediaRtcpCreateParams() *MediaRtcpCreateParams {
	var ()
	return &MediaRtcpCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMediaRtcpCreateParamsWithTimeout creates a new MediaRtcpCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMediaRtcpCreateParamsWithTimeout(timeout time.Duration) *MediaRtcpCreateParams {
	var ()
	return &MediaRtcpCreateParams{

		timeout: timeout,
	}
}

// NewMediaRtcpCreateParamsWithContext creates a new MediaRtcpCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMediaRtcpCreateParamsWithContext(ctx context.Context) *MediaRtcpCreateParams {
	var ()
	return &MediaRtcpCreateParams{

		Context: ctx,
	}
}

// NewMediaRtcpCreateParamsWithHTTPClient creates a new MediaRtcpCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMediaRtcpCreateParamsWithHTTPClient(client *http.Client) *MediaRtcpCreateParams {
	var ()
	return &MediaRtcpCreateParams{
		HTTPClient: client,
	}
}

/*MediaRtcpCreateParams contains all the parameters to send to the API endpoint
for the media rtcp create operation typically these are written to a http.Request
*/
type MediaRtcpCreateParams struct {

	/*Body
	  bodyには空のJSON文字列("{}"")が必要です

	*/
	Body interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the media rtcp create params
func (o *MediaRtcpCreateParams) WithTimeout(timeout time.Duration) *MediaRtcpCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the media rtcp create params
func (o *MediaRtcpCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the media rtcp create params
func (o *MediaRtcpCreateParams) WithContext(ctx context.Context) *MediaRtcpCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the media rtcp create params
func (o *MediaRtcpCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the media rtcp create params
func (o *MediaRtcpCreateParams) WithHTTPClient(client *http.Client) *MediaRtcpCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the media rtcp create params
func (o *MediaRtcpCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the media rtcp create params
func (o *MediaRtcpCreateParams) WithBody(body interface{}) *MediaRtcpCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the media rtcp create params
func (o *MediaRtcpCreateParams) SetBody(body interface{}) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *MediaRtcpCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
