// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/atotto/skyway-webrtc-gateway-go-client/models"
)

// NewMediaConnectionCreateParams creates a new MediaConnectionCreateParams object
// with the default values initialized.
func NewMediaConnectionCreateParams() *MediaConnectionCreateParams {
	var ()
	return &MediaConnectionCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMediaConnectionCreateParamsWithTimeout creates a new MediaConnectionCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMediaConnectionCreateParamsWithTimeout(timeout time.Duration) *MediaConnectionCreateParams {
	var ()
	return &MediaConnectionCreateParams{

		timeout: timeout,
	}
}

// NewMediaConnectionCreateParamsWithContext creates a new MediaConnectionCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMediaConnectionCreateParamsWithContext(ctx context.Context) *MediaConnectionCreateParams {
	var ()
	return &MediaConnectionCreateParams{

		Context: ctx,
	}
}

// NewMediaConnectionCreateParamsWithHTTPClient creates a new MediaConnectionCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMediaConnectionCreateParamsWithHTTPClient(client *http.Client) *MediaConnectionCreateParams {
	var ()
	return &MediaConnectionCreateParams{
		HTTPClient: client,
	}
}

/*MediaConnectionCreateParams contains all the parameters to send to the API endpoint
for the media connection create operation typically these are written to a http.Request
*/
type MediaConnectionCreateParams struct {

	/*Body
	  転送するMediaについての情報を指定します

	*/
	Body *models.PeerCallOptions

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the media connection create params
func (o *MediaConnectionCreateParams) WithTimeout(timeout time.Duration) *MediaConnectionCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the media connection create params
func (o *MediaConnectionCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the media connection create params
func (o *MediaConnectionCreateParams) WithContext(ctx context.Context) *MediaConnectionCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the media connection create params
func (o *MediaConnectionCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the media connection create params
func (o *MediaConnectionCreateParams) WithHTTPClient(client *http.Client) *MediaConnectionCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the media connection create params
func (o *MediaConnectionCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the media connection create params
func (o *MediaConnectionCreateParams) WithBody(body *models.PeerCallOptions) *MediaConnectionCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the media connection create params
func (o *MediaConnectionCreateParams) SetBody(body *models.PeerCallOptions) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *MediaConnectionCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
