// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/atotto/skyway-webrtc-gateway-go-client/models"
)

// NewMediaConnectionAnswerParams creates a new MediaConnectionAnswerParams object
// with the default values initialized.
func NewMediaConnectionAnswerParams() *MediaConnectionAnswerParams {
	var ()
	return &MediaConnectionAnswerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMediaConnectionAnswerParamsWithTimeout creates a new MediaConnectionAnswerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMediaConnectionAnswerParamsWithTimeout(timeout time.Duration) *MediaConnectionAnswerParams {
	var ()
	return &MediaConnectionAnswerParams{

		timeout: timeout,
	}
}

// NewMediaConnectionAnswerParamsWithContext creates a new MediaConnectionAnswerParams object
// with the default values initialized, and the ability to set a context for a request
func NewMediaConnectionAnswerParamsWithContext(ctx context.Context) *MediaConnectionAnswerParams {
	var ()
	return &MediaConnectionAnswerParams{

		Context: ctx,
	}
}

// NewMediaConnectionAnswerParamsWithHTTPClient creates a new MediaConnectionAnswerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMediaConnectionAnswerParamsWithHTTPClient(client *http.Client) *MediaConnectionAnswerParams {
	var ()
	return &MediaConnectionAnswerParams{
		HTTPClient: client,
	}
}

/*MediaConnectionAnswerParams contains all the parameters to send to the API endpoint
for the media connection answer operation typically these are written to a http.Request
*/
type MediaConnectionAnswerParams struct {

	/*Body
	  相手側のPeerへ送信するMediaの情報を指定します

	*/
	Body *models.MediaConnectionAnswerOptions
	/*MediaConnectionID
	  MediaConnectionを特定するためのidを指定します

	*/
	MediaConnectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the media connection answer params
func (o *MediaConnectionAnswerParams) WithTimeout(timeout time.Duration) *MediaConnectionAnswerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the media connection answer params
func (o *MediaConnectionAnswerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the media connection answer params
func (o *MediaConnectionAnswerParams) WithContext(ctx context.Context) *MediaConnectionAnswerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the media connection answer params
func (o *MediaConnectionAnswerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the media connection answer params
func (o *MediaConnectionAnswerParams) WithHTTPClient(client *http.Client) *MediaConnectionAnswerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the media connection answer params
func (o *MediaConnectionAnswerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the media connection answer params
func (o *MediaConnectionAnswerParams) WithBody(body *models.MediaConnectionAnswerOptions) *MediaConnectionAnswerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the media connection answer params
func (o *MediaConnectionAnswerParams) SetBody(body *models.MediaConnectionAnswerOptions) {
	o.Body = body
}

// WithMediaConnectionID adds the mediaConnectionID to the media connection answer params
func (o *MediaConnectionAnswerParams) WithMediaConnectionID(mediaConnectionID string) *MediaConnectionAnswerParams {
	o.SetMediaConnectionID(mediaConnectionID)
	return o
}

// SetMediaConnectionID adds the mediaConnectionId to the media connection answer params
func (o *MediaConnectionAnswerParams) SetMediaConnectionID(mediaConnectionID string) {
	o.MediaConnectionID = mediaConnectionID
}

// WriteToRequest writes these params to a swagger request
func (o *MediaConnectionAnswerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param media_connection_id
	if err := r.SetPathParam("media_connection_id", o.MediaConnectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
