// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/atotto/skyway-webrtc-gateway-go-client/models"
)

// NewMediaConnectionPliParams creates a new MediaConnectionPliParams object
// with the default values initialized.
func NewMediaConnectionPliParams() *MediaConnectionPliParams {
	var ()
	return &MediaConnectionPliParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMediaConnectionPliParamsWithTimeout creates a new MediaConnectionPliParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMediaConnectionPliParamsWithTimeout(timeout time.Duration) *MediaConnectionPliParams {
	var ()
	return &MediaConnectionPliParams{

		timeout: timeout,
	}
}

// NewMediaConnectionPliParamsWithContext creates a new MediaConnectionPliParams object
// with the default values initialized, and the ability to set a context for a request
func NewMediaConnectionPliParamsWithContext(ctx context.Context) *MediaConnectionPliParams {
	var ()
	return &MediaConnectionPliParams{

		Context: ctx,
	}
}

// NewMediaConnectionPliParamsWithHTTPClient creates a new MediaConnectionPliParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMediaConnectionPliParamsWithHTTPClient(client *http.Client) *MediaConnectionPliParams {
	var ()
	return &MediaConnectionPliParams{
		HTTPClient: client,
	}
}

/*MediaConnectionPliParams contains all the parameters to send to the API endpoint
for the media connection pli operation typically these are written to a http.Request
*/
type MediaConnectionPliParams struct {

	/*Body
	  どのMediaに対するRTCP情報をRedirectするのか特定するために、Mediaの受信に利用しているIPアドレスとポート番号を指定します

	*/
	Body *models.MediaConnectionPliRequestOptions
	/*MediaConnectionID
	  MediaConnectionを特定するためのidを指定します

	*/
	MediaConnectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the media connection pli params
func (o *MediaConnectionPliParams) WithTimeout(timeout time.Duration) *MediaConnectionPliParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the media connection pli params
func (o *MediaConnectionPliParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the media connection pli params
func (o *MediaConnectionPliParams) WithContext(ctx context.Context) *MediaConnectionPliParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the media connection pli params
func (o *MediaConnectionPliParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the media connection pli params
func (o *MediaConnectionPliParams) WithHTTPClient(client *http.Client) *MediaConnectionPliParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the media connection pli params
func (o *MediaConnectionPliParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the media connection pli params
func (o *MediaConnectionPliParams) WithBody(body *models.MediaConnectionPliRequestOptions) *MediaConnectionPliParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the media connection pli params
func (o *MediaConnectionPliParams) SetBody(body *models.MediaConnectionPliRequestOptions) {
	o.Body = body
}

// WithMediaConnectionID adds the mediaConnectionID to the media connection pli params
func (o *MediaConnectionPliParams) WithMediaConnectionID(mediaConnectionID string) *MediaConnectionPliParams {
	o.SetMediaConnectionID(mediaConnectionID)
	return o
}

// SetMediaConnectionID adds the mediaConnectionId to the media connection pli params
func (o *MediaConnectionPliParams) SetMediaConnectionID(mediaConnectionID string) {
	o.MediaConnectionID = mediaConnectionID
}

// WriteToRequest writes these params to a swagger request
func (o *MediaConnectionPliParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param media_connection_id
	if err := r.SetPathParam("media_connection_id", o.MediaConnectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
