// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMediaConnectionCloseParams creates a new MediaConnectionCloseParams object
// with the default values initialized.
func NewMediaConnectionCloseParams() *MediaConnectionCloseParams {
	var ()
	return &MediaConnectionCloseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMediaConnectionCloseParamsWithTimeout creates a new MediaConnectionCloseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMediaConnectionCloseParamsWithTimeout(timeout time.Duration) *MediaConnectionCloseParams {
	var ()
	return &MediaConnectionCloseParams{

		timeout: timeout,
	}
}

// NewMediaConnectionCloseParamsWithContext creates a new MediaConnectionCloseParams object
// with the default values initialized, and the ability to set a context for a request
func NewMediaConnectionCloseParamsWithContext(ctx context.Context) *MediaConnectionCloseParams {
	var ()
	return &MediaConnectionCloseParams{

		Context: ctx,
	}
}

// NewMediaConnectionCloseParamsWithHTTPClient creates a new MediaConnectionCloseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMediaConnectionCloseParamsWithHTTPClient(client *http.Client) *MediaConnectionCloseParams {
	var ()
	return &MediaConnectionCloseParams{
		HTTPClient: client,
	}
}

/*MediaConnectionCloseParams contains all the parameters to send to the API endpoint
for the media connection close operation typically these are written to a http.Request
*/
type MediaConnectionCloseParams struct {

	/*MediaConnectionID
	  MediaConnectionを特定するためのidを指定します

	*/
	MediaConnectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the media connection close params
func (o *MediaConnectionCloseParams) WithTimeout(timeout time.Duration) *MediaConnectionCloseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the media connection close params
func (o *MediaConnectionCloseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the media connection close params
func (o *MediaConnectionCloseParams) WithContext(ctx context.Context) *MediaConnectionCloseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the media connection close params
func (o *MediaConnectionCloseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the media connection close params
func (o *MediaConnectionCloseParams) WithHTTPClient(client *http.Client) *MediaConnectionCloseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the media connection close params
func (o *MediaConnectionCloseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMediaConnectionID adds the mediaConnectionID to the media connection close params
func (o *MediaConnectionCloseParams) WithMediaConnectionID(mediaConnectionID string) *MediaConnectionCloseParams {
	o.SetMediaConnectionID(mediaConnectionID)
	return o
}

// SetMediaConnectionID adds the mediaConnectionId to the media connection close params
func (o *MediaConnectionCloseParams) SetMediaConnectionID(mediaConnectionID string) {
	o.MediaConnectionID = mediaConnectionID
}

// WriteToRequest writes these params to a swagger request
func (o *MediaConnectionCloseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param media_connection_id
	if err := r.SetPathParam("media_connection_id", o.MediaConnectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
