// Code generated by go-swagger; DO NOT EDIT.

package media

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewMediaRtcpDeleteParams creates a new MediaRtcpDeleteParams object
// with the default values initialized.
func NewMediaRtcpDeleteParams() *MediaRtcpDeleteParams {
	var ()
	return &MediaRtcpDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMediaRtcpDeleteParamsWithTimeout creates a new MediaRtcpDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMediaRtcpDeleteParamsWithTimeout(timeout time.Duration) *MediaRtcpDeleteParams {
	var ()
	return &MediaRtcpDeleteParams{

		timeout: timeout,
	}
}

// NewMediaRtcpDeleteParamsWithContext creates a new MediaRtcpDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewMediaRtcpDeleteParamsWithContext(ctx context.Context) *MediaRtcpDeleteParams {
	var ()
	return &MediaRtcpDeleteParams{

		Context: ctx,
	}
}

// NewMediaRtcpDeleteParamsWithHTTPClient creates a new MediaRtcpDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMediaRtcpDeleteParamsWithHTTPClient(client *http.Client) *MediaRtcpDeleteParams {
	var ()
	return &MediaRtcpDeleteParams{
		HTTPClient: client,
	}
}

/*MediaRtcpDeleteParams contains all the parameters to send to the API endpoint
for the media rtcp delete operation typically these are written to a http.Request
*/
type MediaRtcpDeleteParams struct {

	/*RtcpID
	  RTCPを特定するためのIDを指定します

	*/
	RtcpID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the media rtcp delete params
func (o *MediaRtcpDeleteParams) WithTimeout(timeout time.Duration) *MediaRtcpDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the media rtcp delete params
func (o *MediaRtcpDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the media rtcp delete params
func (o *MediaRtcpDeleteParams) WithContext(ctx context.Context) *MediaRtcpDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the media rtcp delete params
func (o *MediaRtcpDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the media rtcp delete params
func (o *MediaRtcpDeleteParams) WithHTTPClient(client *http.Client) *MediaRtcpDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the media rtcp delete params
func (o *MediaRtcpDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRtcpID adds the rtcpID to the media rtcp delete params
func (o *MediaRtcpDeleteParams) WithRtcpID(rtcpID string) *MediaRtcpDeleteParams {
	o.SetRtcpID(rtcpID)
	return o
}

// SetRtcpID adds the rtcpId to the media rtcp delete params
func (o *MediaRtcpDeleteParams) SetRtcpID(rtcpID string) {
	o.RtcpID = rtcpID
}

// WriteToRequest writes these params to a swagger request
func (o *MediaRtcpDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rtcp_id
	if err := r.SetPathParam("rtcp_id", o.RtcpID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
