// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDataDeleteParams creates a new DataDeleteParams object
// with the default values initialized.
func NewDataDeleteParams() *DataDeleteParams {
	var ()
	return &DataDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDataDeleteParamsWithTimeout creates a new DataDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDataDeleteParamsWithTimeout(timeout time.Duration) *DataDeleteParams {
	var ()
	return &DataDeleteParams{

		timeout: timeout,
	}
}

// NewDataDeleteParamsWithContext creates a new DataDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewDataDeleteParamsWithContext(ctx context.Context) *DataDeleteParams {
	var ()
	return &DataDeleteParams{

		Context: ctx,
	}
}

// NewDataDeleteParamsWithHTTPClient creates a new DataDeleteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDataDeleteParamsWithHTTPClient(client *http.Client) *DataDeleteParams {
	var ()
	return &DataDeleteParams{
		HTTPClient: client,
	}
}

/*DataDeleteParams contains all the parameters to send to the API endpoint
for the data delete operation typically these are written to a http.Request
*/
type DataDeleteParams struct {

	/*DataID
	  Dataを特定するためのIDを指定します

	*/
	DataID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the data delete params
func (o *DataDeleteParams) WithTimeout(timeout time.Duration) *DataDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the data delete params
func (o *DataDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the data delete params
func (o *DataDeleteParams) WithContext(ctx context.Context) *DataDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the data delete params
func (o *DataDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the data delete params
func (o *DataDeleteParams) WithHTTPClient(client *http.Client) *DataDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the data delete params
func (o *DataDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDataID adds the dataID to the data delete params
func (o *DataDeleteParams) WithDataID(dataID string) *DataDeleteParams {
	o.SetDataID(dataID)
	return o
}

// SetDataID adds the dataId to the data delete params
func (o *DataDeleteParams) SetDataID(dataID string) {
	o.DataID = dataID
}

// WriteToRequest writes these params to a swagger request
func (o *DataDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param data_id
	if err := r.SetPathParam("data_id", o.DataID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
