// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDataParams creates a new DataParams object
// with the default values initialized.
func NewDataParams() *DataParams {
	var ()
	return &DataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDataParamsWithTimeout creates a new DataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDataParamsWithTimeout(timeout time.Duration) *DataParams {
	var ()
	return &DataParams{

		timeout: timeout,
	}
}

// NewDataParamsWithContext creates a new DataParams object
// with the default values initialized, and the ability to set a context for a request
func NewDataParamsWithContext(ctx context.Context) *DataParams {
	var ()
	return &DataParams{

		Context: ctx,
	}
}

// NewDataParamsWithHTTPClient creates a new DataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDataParamsWithHTTPClient(client *http.Client) *DataParams {
	var ()
	return &DataParams{
		HTTPClient: client,
	}
}

/*DataParams contains all the parameters to send to the API endpoint
for the data operation typically these are written to a http.Request
*/
type DataParams struct {

	/*Body
	  bodyには空のJSON文字列("{}")が必要です

	*/
	Body interface{}

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the data params
func (o *DataParams) WithTimeout(timeout time.Duration) *DataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the data params
func (o *DataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the data params
func (o *DataParams) WithContext(ctx context.Context) *DataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the data params
func (o *DataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the data params
func (o *DataParams) WithHTTPClient(client *http.Client) *DataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the data params
func (o *DataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the data params
func (o *DataParams) WithBody(body interface{}) *DataParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the data params
func (o *DataParams) SetBody(body interface{}) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
