// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/atotto/skyway-webrtc-gateway-go-client/models"
)

// NewDataConnectionsCreateParams creates a new DataConnectionsCreateParams object
// with the default values initialized.
func NewDataConnectionsCreateParams() *DataConnectionsCreateParams {
	var ()
	return &DataConnectionsCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDataConnectionsCreateParamsWithTimeout creates a new DataConnectionsCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDataConnectionsCreateParamsWithTimeout(timeout time.Duration) *DataConnectionsCreateParams {
	var ()
	return &DataConnectionsCreateParams{

		timeout: timeout,
	}
}

// NewDataConnectionsCreateParamsWithContext creates a new DataConnectionsCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDataConnectionsCreateParamsWithContext(ctx context.Context) *DataConnectionsCreateParams {
	var ()
	return &DataConnectionsCreateParams{

		Context: ctx,
	}
}

// NewDataConnectionsCreateParamsWithHTTPClient creates a new DataConnectionsCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDataConnectionsCreateParamsWithHTTPClient(client *http.Client) *DataConnectionsCreateParams {
	var ()
	return &DataConnectionsCreateParams{
		HTTPClient: client,
	}
}

/*DataConnectionsCreateParams contains all the parameters to send to the API endpoint
for the data connections create operation typically these are written to a http.Request
*/
type DataConnectionsCreateParams struct {

	/*Body
	  転送するDataについての情報を指定します

	*/
	Body *models.PeerConnectOptions

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the data connections create params
func (o *DataConnectionsCreateParams) WithTimeout(timeout time.Duration) *DataConnectionsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the data connections create params
func (o *DataConnectionsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the data connections create params
func (o *DataConnectionsCreateParams) WithContext(ctx context.Context) *DataConnectionsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the data connections create params
func (o *DataConnectionsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the data connections create params
func (o *DataConnectionsCreateParams) WithHTTPClient(client *http.Client) *DataConnectionsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the data connections create params
func (o *DataConnectionsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the data connections create params
func (o *DataConnectionsCreateParams) WithBody(body *models.PeerConnectOptions) *DataConnectionsCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the data connections create params
func (o *DataConnectionsCreateParams) SetBody(body *models.PeerConnectOptions) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DataConnectionsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
