// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDataConnectionCloseParams creates a new DataConnectionCloseParams object
// with the default values initialized.
func NewDataConnectionCloseParams() *DataConnectionCloseParams {
	var ()
	return &DataConnectionCloseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDataConnectionCloseParamsWithTimeout creates a new DataConnectionCloseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDataConnectionCloseParamsWithTimeout(timeout time.Duration) *DataConnectionCloseParams {
	var ()
	return &DataConnectionCloseParams{

		timeout: timeout,
	}
}

// NewDataConnectionCloseParamsWithContext creates a new DataConnectionCloseParams object
// with the default values initialized, and the ability to set a context for a request
func NewDataConnectionCloseParamsWithContext(ctx context.Context) *DataConnectionCloseParams {
	var ()
	return &DataConnectionCloseParams{

		Context: ctx,
	}
}

// NewDataConnectionCloseParamsWithHTTPClient creates a new DataConnectionCloseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDataConnectionCloseParamsWithHTTPClient(client *http.Client) *DataConnectionCloseParams {
	var ()
	return &DataConnectionCloseParams{
		HTTPClient: client,
	}
}

/*DataConnectionCloseParams contains all the parameters to send to the API endpoint
for the data connection close operation typically these are written to a http.Request
*/
type DataConnectionCloseParams struct {

	/*DataConnectionID
	  DataConnectionを特定するためのidを指定します

	*/
	DataConnectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the data connection close params
func (o *DataConnectionCloseParams) WithTimeout(timeout time.Duration) *DataConnectionCloseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the data connection close params
func (o *DataConnectionCloseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the data connection close params
func (o *DataConnectionCloseParams) WithContext(ctx context.Context) *DataConnectionCloseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the data connection close params
func (o *DataConnectionCloseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the data connection close params
func (o *DataConnectionCloseParams) WithHTTPClient(client *http.Client) *DataConnectionCloseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the data connection close params
func (o *DataConnectionCloseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDataConnectionID adds the dataConnectionID to the data connection close params
func (o *DataConnectionCloseParams) WithDataConnectionID(dataConnectionID string) *DataConnectionCloseParams {
	o.SetDataConnectionID(dataConnectionID)
	return o
}

// SetDataConnectionID adds the dataConnectionId to the data connection close params
func (o *DataConnectionCloseParams) SetDataConnectionID(dataConnectionID string) {
	o.DataConnectionID = dataConnectionID
}

// WriteToRequest writes these params to a swagger request
func (o *DataConnectionCloseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param data_connection_id
	if err := r.SetPathParam("data_connection_id", o.DataConnectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
