// Code generated by go-swagger; DO NOT EDIT.

package data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDataConnectionStatusParams creates a new DataConnectionStatusParams object
// with the default values initialized.
func NewDataConnectionStatusParams() *DataConnectionStatusParams {
	var ()
	return &DataConnectionStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDataConnectionStatusParamsWithTimeout creates a new DataConnectionStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDataConnectionStatusParamsWithTimeout(timeout time.Duration) *DataConnectionStatusParams {
	var ()
	return &DataConnectionStatusParams{

		timeout: timeout,
	}
}

// NewDataConnectionStatusParamsWithContext creates a new DataConnectionStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewDataConnectionStatusParamsWithContext(ctx context.Context) *DataConnectionStatusParams {
	var ()
	return &DataConnectionStatusParams{

		Context: ctx,
	}
}

// NewDataConnectionStatusParamsWithHTTPClient creates a new DataConnectionStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDataConnectionStatusParamsWithHTTPClient(client *http.Client) *DataConnectionStatusParams {
	var ()
	return &DataConnectionStatusParams{
		HTTPClient: client,
	}
}

/*DataConnectionStatusParams contains all the parameters to send to the API endpoint
for the data connection status operation typically these are written to a http.Request
*/
type DataConnectionStatusParams struct {

	/*DataConnectionID
	  DataConnectionを特定するためのIDを指定します

	*/
	DataConnectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the data connection status params
func (o *DataConnectionStatusParams) WithTimeout(timeout time.Duration) *DataConnectionStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the data connection status params
func (o *DataConnectionStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the data connection status params
func (o *DataConnectionStatusParams) WithContext(ctx context.Context) *DataConnectionStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the data connection status params
func (o *DataConnectionStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the data connection status params
func (o *DataConnectionStatusParams) WithHTTPClient(client *http.Client) *DataConnectionStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the data connection status params
func (o *DataConnectionStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDataConnectionID adds the dataConnectionID to the data connection status params
func (o *DataConnectionStatusParams) WithDataConnectionID(dataConnectionID string) *DataConnectionStatusParams {
	o.SetDataConnectionID(dataConnectionID)
	return o
}

// SetDataConnectionID adds the dataConnectionId to the data connection status params
func (o *DataConnectionStatusParams) SetDataConnectionID(dataConnectionID string) {
	o.DataConnectionID = dataConnectionID
}

// WriteToRequest writes these params to a swagger request
func (o *DataConnectionStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param data_connection_id
	if err := r.SetPathParam("data_connection_id", o.DataConnectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
