// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CallParametsers call及びstreamイベントのときのみ含まれます
// swagger:model CallParametsers
type CallParametsers struct {

	// 相手側からのCallに応答するのに必要なIDです
	// Required: true
	MediaConnectionID *string `json:"media_connection_id"`
}

// Validate validates this call parametsers
func (m *CallParametsers) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMediaConnectionID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CallParametsers) validateMediaConnectionID(formats strfmt.Registry) error {

	if err := validate.Required("media_connection_id", "body", m.MediaConnectionID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CallParametsers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CallParametsers) UnmarshalBinary(b []byte) error {
	var res CallParametsers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
