// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DataParametsers OnDataConnectionイベントのときのみ含まれます
// swagger:model DataParametsers
type DataParametsers struct {

	// 相手側からのConnectに応答するのに必要なIDです
	// Required: true
	DataConnectionID *string `json:"data_connection_id"`
}

// Validate validates this data parametsers
func (m *DataParametsers) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDataConnectionID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DataParametsers) validateDataConnectionID(formats strfmt.Registry) error {

	if err := validate.Required("data_connection_id", "body", m.DataConnectionID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DataParametsers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataParametsers) UnmarshalBinary(b []byte) error {
	var res DataParametsers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
