// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DataConnectionPutOptions data connection put options
// swagger:model DataConnectionPutOptions
type DataConnectionPutOptions struct {

	// feed params
	FeedParams *DataConnectionFeedOptions `json:"feed_params,omitempty"`

	// redirect params
	RedirectParams *DataConnectionRedirectOptions `json:"redirect_params,omitempty"`
}

// Validate validates this data connection put options
func (m *DataConnectionPutOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFeedParams(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRedirectParams(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DataConnectionPutOptions) validateFeedParams(formats strfmt.Registry) error {

	if swag.IsZero(m.FeedParams) { // not required
		return nil
	}

	if m.FeedParams != nil {
		if err := m.FeedParams.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("feed_params")
			}
			return err
		}
	}

	return nil
}

func (m *DataConnectionPutOptions) validateRedirectParams(formats strfmt.Registry) error {

	if swag.IsZero(m.RedirectParams) { // not required
		return nil
	}

	if m.RedirectParams != nil {
		if err := m.RedirectParams.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("redirect_params")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DataConnectionPutOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DataConnectionPutOptions) UnmarshalBinary(b []byte) error {
	var res DataConnectionPutOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
