// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DcInit dc init
// swagger:model DcInit
type DcInit struct {

	// id
	ID int64 `json:"id,omitempty"`

	// max packet life time
	MaxPacketLifeTime int64 `json:"maxPacketLifeTime,omitempty"`

	// max retransmits
	MaxRetransmits int64 `json:"maxRetransmits,omitempty"`

	// negotiated
	Negotiated bool `json:"negotiated,omitempty"`

	// ordered
	Ordered bool `json:"ordered,omitempty"`

	// priority
	Priority string `json:"priority,omitempty"`

	// protocol
	Protocol string `json:"protocol,omitempty"`
}

// Validate validates this dc init
func (m *DcInit) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DcInit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DcInit) UnmarshalBinary(b []byte) error {
	var res DcInit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
