// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MediaOptions media options
// swagger:model MediaOptions
type MediaOptions struct {

	// MediaがVideoかどうかを指定します。falseの場合はAudioとして扱われます
	// Required: true
	IsVideo *bool `json:"is_video"`
}

// Validate validates this media options
func (m *MediaOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIsVideo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MediaOptions) validateIsVideo(formats strfmt.Registry) error {

	if err := validate.Required("is_video", "body", m.IsVideo); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MediaOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaOptions) UnmarshalBinary(b []byte) error {
	var res MediaOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
