// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MediaConnectionPliRequestOptions どのMediaに対するRTCP情報をRedirectするのか特定するために、Mediaの受信に利用しているIPアドレスとポート番号を指定します
// swagger:model MediaConnectionPliRequestOptions
type MediaConnectionPliRequestOptions struct {

	// Mediaを待ち受けるIPv4アドレスです。ip_v4もしくはip_v6のいずれかは必須です
	IPV4 string `json:"ip_v4,omitempty"`

	// Mediaを待ち受けるIPv6アドレスです。ip_v4もしくはip_v6のいずれかは必須です
	IPV6 string `json:"ip_v6,omitempty"`

	// Mediaを待ち受けるポート番号です
	// Required: true
	Port *uint16 `json:"port"`
}

// Validate validates this media connection pli request options
func (m *MediaConnectionPliRequestOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MediaConnectionPliRequestOptions) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MediaConnectionPliRequestOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaConnectionPliRequestOptions) UnmarshalBinary(b []byte) error {
	var res MediaConnectionPliRequestOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
