// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MediaRedirectOptions media redirect options
// swagger:model MediaRedirectOptions
type MediaRedirectOptions struct {

	// audio
	Audio *MediaRedirectOptionsAudio `json:"audio,omitempty"`

	// video
	Video *MediaRedirectOptionsVideo `json:"video,omitempty"`
}

// Validate validates this media redirect options
func (m *MediaRedirectOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAudio(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVideo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MediaRedirectOptions) validateAudio(formats strfmt.Registry) error {

	if swag.IsZero(m.Audio) { // not required
		return nil
	}

	if m.Audio != nil {
		if err := m.Audio.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("audio")
			}
			return err
		}
	}

	return nil
}

func (m *MediaRedirectOptions) validateVideo(formats strfmt.Registry) error {

	if swag.IsZero(m.Video) { // not required
		return nil
	}

	if m.Video != nil {
		if err := m.Video.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("video")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MediaRedirectOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaRedirectOptions) UnmarshalBinary(b []byte) error {
	var res MediaRedirectOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// MediaRedirectOptionsAudio media redirect options audio
// swagger:model MediaRedirectOptionsAudio
type MediaRedirectOptionsAudio struct {

	// Mediaの転送先IPv4アドレスを指定します。ip_v4またはip_v6アドレスのいずれかの情報は必須です。両方が指定された場合はip_v4が優先されます
	IPV4 string `json:"ip_v4,omitempty"`

	// Mediaの転送先IPv6アドレスを指定します。ip_v4またはip_v6アドレスのいずれかの情報は必須です。両方が指定された場合はip_v4が優先されます
	IPV6 string `json:"ip_v6,omitempty"`

	// port
	Port uint16 `json:"port,omitempty"`
}

// Validate validates this media redirect options audio
func (m *MediaRedirectOptionsAudio) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MediaRedirectOptionsAudio) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaRedirectOptionsAudio) UnmarshalBinary(b []byte) error {
	var res MediaRedirectOptionsAudio
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// MediaRedirectOptionsVideo media redirect options video
// swagger:model MediaRedirectOptionsVideo
type MediaRedirectOptionsVideo struct {

	// Mediaの転送先IPv4アドレスを指定します。ip_v4またはip_v6アドレスのいずれかの情報は必須です。両方が指定された場合はip_v4が優先されます
	IPV4 string `json:"ip_v4,omitempty"`

	// Mediaの転送先IPv6アドレスを指定します。ip_v4またはip_v6アドレスのいずれかの情報は必須です。両方が指定された場合はip_v4が優先されます
	IPV6 string `json:"ip_v6,omitempty"`

	// port
	Port uint16 `json:"port,omitempty"`
}

// Validate validates this media redirect options video
func (m *MediaRedirectOptionsVideo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MediaRedirectOptionsVideo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaRedirectOptionsVideo) UnmarshalBinary(b []byte) error {
	var res MediaRedirectOptionsVideo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
