// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MediaConnectionAnswerResponse media connection answer response
// swagger:model MediaConnectionAnswerResponse
type MediaConnectionAnswerResponse struct {

	// command type
	// Required: true
	CommandType *string `json:"command_type"`

	// params
	// Required: true
	Params *MediaConnectionAnswerResponseParams `json:"params"`
}

// Validate validates this media connection answer response
func (m *MediaConnectionAnswerResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommandType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParams(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MediaConnectionAnswerResponse) validateCommandType(formats strfmt.Registry) error {

	if err := validate.Required("command_type", "body", m.CommandType); err != nil {
		return err
	}

	return nil
}

func (m *MediaConnectionAnswerResponse) validateParams(formats strfmt.Registry) error {

	if err := validate.Required("params", "body", m.Params); err != nil {
		return err
	}

	if m.Params != nil {
		if err := m.Params.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("params")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MediaConnectionAnswerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaConnectionAnswerResponse) UnmarshalBinary(b []byte) error {
	var res MediaConnectionAnswerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// MediaConnectionAnswerResponseParams media connection answer response params
// swagger:model MediaConnectionAnswerResponseParams
type MediaConnectionAnswerResponseParams struct {

	// Audioを特定するためのIDです
	AudioID string `json:"audio_id,omitempty"`

	// Audioを受け取るNative Clientのポート番号を指定します
	AudioPort uint16 `json:"audio_port,omitempty"`

	// Videoを特定するためのIDです
	VideoID string `json:"video_id,omitempty"`

	// Videoを受け取るNative Clientのポート番号を指定します
	VideoPort uint16 `json:"video_port,omitempty"`
}

// Validate validates this media connection answer response params
func (m *MediaConnectionAnswerResponseParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MediaConnectionAnswerResponseParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaConnectionAnswerResponseParams) UnmarshalBinary(b []byte) error {
	var res MediaConnectionAnswerResponseParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
