// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PeerCallResponse peer call response
// swagger:model PeerCallResponse
type PeerCallResponse struct {

	// command type
	// Required: true
	CommandType *string `json:"command_type"`

	// params
	// Required: true
	Params *PeerCallResponseParams `json:"params"`
}

// Validate validates this peer call response
func (m *PeerCallResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommandType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateParams(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerCallResponse) validateCommandType(formats strfmt.Registry) error {

	if err := validate.Required("command_type", "body", m.CommandType); err != nil {
		return err
	}

	return nil
}

func (m *PeerCallResponse) validateParams(formats strfmt.Registry) error {

	if err := validate.Required("params", "body", m.Params); err != nil {
		return err
	}

	if m.Params != nil {
		if err := m.Params.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("params")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PeerCallResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerCallResponse) UnmarshalBinary(b []byte) error {
	var res PeerCallResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PeerCallResponseParams peer call response params
// swagger:model PeerCallResponseParams
type PeerCallResponseParams struct {

	// MediaConnectionを特定するためのIDです
	MediaConnectionID string `json:"media_connection_id,omitempty"`
}

// Validate validates this peer call response params
func (m *PeerCallResponseParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PeerCallResponseParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerCallResponseParams) UnmarshalBinary(b []byte) error {
	var res PeerCallResponseParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
