// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PeerParametsers openイベントのときのみ含まれます
// swagger:model PeerParametsers
type PeerParametsers struct {

	// Peerを特定するためのIDです
	// Required: true
	PeerID *string `json:"peer_id"`

	// Peerを利用するために必要なtokenです。
	Token string `json:"token,omitempty"`
}

// Validate validates this peer parametsers
func (m *PeerParametsers) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePeerID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerParametsers) validatePeerID(formats strfmt.Registry) error {

	if err := validate.Required("peer_id", "body", m.PeerID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PeerParametsers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerParametsers) UnmarshalBinary(b []byte) error {
	var res PeerParametsers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
