// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PeerStatusMessage peer status message
// swagger:model PeerStatusMessage
type PeerStatusMessage struct {

	// disconnected
	// Required: true
	Disconnected *bool `json:"disconnected"`

	// Peerオブジェクトを特定するためのIDです
	// Required: true
	PeerID *string `json:"peer_id"`
}

// Validate validates this peer status message
func (m *PeerStatusMessage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDisconnected(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePeerID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PeerStatusMessage) validateDisconnected(formats strfmt.Registry) error {

	if err := validate.Required("disconnected", "body", m.Disconnected); err != nil {
		return err
	}

	return nil
}

func (m *PeerStatusMessage) validatePeerID(formats strfmt.Registry) error {

	if err := validate.Required("peer_id", "body", m.PeerID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PeerStatusMessage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PeerStatusMessage) UnmarshalBinary(b []byte) error {
	var res PeerStatusMessage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
